export enum CrewAssignmentPosition {
  CAPTAIN = 'CAPTAIN',
  FIRST_OFFICER = 'FIRST_OFFICER',
  SENIOR_CABIN_CREW = 'SENIOR_CABIN_CREW',
  CABIN_CREW = 'CABIN_CREW',
  TECHNICIAN = 'TECHNICIAN',
  STEWARDESS = 'STEWARDESS',
}
