export enum FlightStatus {
  AWAITING_CREW = 'AWAITING_CREW',
  SCHEDULED = 'SCHEDULED',
  BOARDING = 'BOARDING',
  DELAYED = 'DELAYED',
  IN_AIR = 'IN_AIR',
  LANDED = 'LANDED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}
